// ─────────────────────────────────────────────────────────────────────────────
//  ResumeForge — Help & Reference
//  Imported by the Help modal; each section is a self-contained object so the
//  UI can render tabs / accordions without parsing raw text.
// ─────────────────────────────────────────────────────────────────────────────

export interface HelpSection {
  id: string;
  title: string;
  intro: string;
  groups: HelpGroup[];
}

export interface HelpGroup {
  heading: string;
  items: HelpItem[];
}

export interface HelpItem {
  label: string;
  syntax: string;
  result: string;
  note?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
//  GENERAL
// ─────────────────────────────────────────────────────────────────────────────

export const GENERAL_HELP = `
ResumeForge lets you write your resume in three formats — Markdown, LaTeX, or plain HTML — and see a live A4 preview as you type.

HOW IT WORKS
  1. Pick a mode (Markdown / LaTeX / HTML) from the toolbar.
  2. Write or paste your content in the left editor.
  3. The right panel shows a live preview that looks exactly like the printed PDF.
  4. Click any text in the preview to open the Style Panel on the right — you can change the text, font size, and colour directly, then click "↗ Go to code" to jump to that line in the editor.
  5. When you are happy, click "Export PDF" in the toolbar to download a print-ready PDF.

STYLE PANEL (click any text in preview)
  • Text      — edit the text content inline; changes are reflected in your source code automatically.
  • Size (px) — override the font size of that specific element.
  • Color     — pick a colour for that element.
  • ↗ Go to code — scrolls the editor to the exact line and highlights it in blue.

THEMES & FONTS
  • Every mode has a set of built-in themes (e.g. Classic, Modern, Minimal).
  • You can also pick a global font from the toolbar font picker — it overrides the theme font on every element.

EXPORT
  • The PDF is generated by printing the preview iframe, so what you see is exactly what you get.
  • Content that overflows the A4 width is clipped (it will not bleed into the margins).
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
//  MARKDOWN
// ─────────────────────────────────────────────────────────────────────────────

export const MARKDOWN_HELP: HelpSection = {
  id: "markdown",
  title: "Markdown Mode",
  intro: `
Markdown is the easiest way to write a resume. You write plain text with simple symbols for formatting and the app converts it to a styled document automatically.

Parser: marked v14  (https://marked.js.org)
Spec:   GitHub Flavored Markdown (GFM) — tables, strikethrough, and task lists are all supported.
Docs:   https://marked.js.org/using_pro
        https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
  `.trim(),
  groups: [
    {
      heading: "Headings",
      items: [
        { label: "Section title (large)",  syntax: "# My Name",           result: "Large heading — use for your name at the top" },
        { label: "Section title (medium)", syntax: "## Experience",        result: "Medium heading — use for resume sections" },
        { label: "Sub-heading",            syntax: "### Job Title",        result: "Smaller heading — use for job titles or companies" },
        { label: "Small label",            syntax: "#### Detail",          result: "Smallest heading — rarely needed" },
      ],
    },
    {
      heading: "Text Formatting",
      items: [
        { label: "Bold",          syntax: "**bold text**",          result: "Bold text — great for company names or skills" },
        { label: "Italic",        syntax: "_italic text_",          result: "Italic text — good for job titles or emphasis" },
        { label: "Bold + Italic", syntax: "**_both_**",             result: "Bold and italic together" },
        { label: "Inline code",   syntax: "`JavaScript`",           result: "Monospace code text — useful for tech skills" },
        { label: "Horizontal rule (divider)", syntax: "---",        result: "A thin horizontal line to separate sections" },
      ],
    },
    {
      heading: "Lists",
      items: [
        { label: "Bullet list",   syntax: "- Did something\n- Did another thing", result: "Unordered bullet list — use for achievements or skills" },
        { label: "Numbered list", syntax: "1. First\n2. Second",    result: "Ordered numbered list" },
        { label: "Nested list",   syntax: "- Item\n  - Sub-item",   result: "Two spaces before the dash to indent" },
      ],
    },
    {
      heading: "Links",
      items: [
        { label: "Hyperlink",     syntax: "[GitHub](https://github.com/you)", result: "Clickable link — shows 'GitHub' as the label" },
        { label: "Bare URL",      syntax: "https://github.com/you",           result: "Raw URL — auto-linked in the preview" },
      ],
    },
    {
      heading: "Tables",
      items: [
        {
          label: "Table",
          syntax: "| Skill | Level |\n|-------|-------|\n| React | Expert |",
          result: "A table with borders — useful for skills matrices",
          note: "Columns are separated by | and the dashes row creates the header.",
        },
      ],
    },
    {
      heading: "Inline Style Override",
      items: [
        {
          label: "Custom colour / size on a word",
          syntax: '<span style="color:#e11d48;font-size:13px">Remote</span>',
          result: "Any inline HTML is accepted — wrap text in a <span> with a style attribute to override colour or size for just that word.",
          note: "This is the same HTML the Style Panel writes automatically when you use the color or size controls.",
        },
      ],
    },
    {
      heading: "Tips",
      items: [
        { label: "Blank line between blocks", syntax: "(empty line)", result: "Always leave a blank line between headings, paragraphs, and lists. Without it, content merges into one paragraph." },
        { label: "Non-breaking space",        syntax: "&nbsp;",        result: "Prevents a line break between two words — e.g. 'Jan&nbsp;2024'" },
        { label: "Em dash",                   syntax: "—",             result: "Paste the — character directly; it renders correctly." },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  LATEX
// ─────────────────────────────────────────────────────────────────────────────

export const LATEX_HELP: HelpSection = {
  id: "latex",
  title: "LaTeX Mode",
  intro: `
LaTeX mode gives you fine-grained control over layout using familiar LaTeX commands. The parser is a custom regex-based converter (built into this app — no external LaTeX engine is needed), so only a curated subset of commands is supported.

Parser: ResumeForge built-in LaTeX renderer (helper/parsers.ts → parseLatex)
  — NOT a full LaTeX engine. Unsupported commands are stripped silently.
  — For full LaTeX rendering see: https://www.overleaf.com

Sanitiser: DOMPurify (https://github.com/cure53/DOMPurify)
  — Scripts and unsafe attributes are stripped from the output for security.

Structure: Wrap all content inside \\begin{document} ... \\end{document}.
  — Anything outside this block (preamble, \\usepackage, etc.) is ignored.
  `.trim(),
  groups: [
    {
      heading: "Document Structure",
      items: [
        {
          label: "Document wrapper",
          syntax: "\\begin{document}\n  ...\n\\end{document}",
          result: "Everything inside this block is rendered. Content outside (preamble) is ignored.",
        },
        {
          label: "Comment (ignored)",
          syntax: "% This is a comment",
          result: "Lines starting with % are stripped — use them for notes to yourself.",
        },
        {
          label: "New page",
          syntax: "\\newpage",
          result: "Forces a page break at that position.",
        },
      ],
    },
    {
      heading: "Resume-Specific Commands (built-in)",
      items: [
        {
          label: "Section heading",
          syntax: "\\rsection{Experience}",
          result: "Renders a styled section heading using the active theme's h2 style.",
          note: "This is the preferred way to create section dividers. Style is controlled by the theme.",
        },
        {
          label: "Job entry",
          syntax: "\\rjob{Company Name}{Job Title}{Jan 2022 – Present}",
          result: "Renders a job block: company as h3, title as h4, date aligned on the right.",
          note: "Arguments: {company}{title}{date}",
        },
        {
          label: "Inline style override",
          syntax: "\\rfstyle{color: #e11d48; font-size: 13px}{Remote}",
          result: "Wraps the text in a <span> with the given CSS. This is what the Style Panel writes automatically.",
          note: "Arguments: {CSS properties}{text to style}",
        },
      ],
    },
    {
      heading: "Text Formatting",
      items: [
        { label: "Bold",         syntax: "\\textbf{text}",    result: "Bold text" },
        { label: "Italic",       syntax: "\\textit{text}",    result: "Italic text" },
        { label: "Emphasise",    syntax: "\\emph{text}",      result: "Italic (same as \\textit for resumes)" },
        { label: "Small caps",   syntax: "\\textsc{text}",    result: "UPPERCASE with wider letter-spacing — good for labels" },
        { label: "Line break",   syntax: "\\\\",              result: "Forces a line break (like pressing Enter once)" },
        { label: "Horizontal rule", syntax: "\\rule{\\linewidth}{0.4pt}", result: "A full-width horizontal divider line" },
      ],
    },
    {
      heading: "Font Size Commands (inside { })",
      items: [
        { label: "Huge",        syntax: "{\\Huge John Smith}",      result: "Very large text (~36px) — great for your name" },
        { label: "huge",        syntax: "{\\huge Section}",          result: "Large text (~30px)" },
        { label: "LARGE",       syntax: "{\\LARGE Title}",           result: "Larger text (~24px)" },
        { label: "Large",       syntax: "{\\Large Title}",           result: "Large text (~20px)" },
        { label: "large",       syntax: "{\\large text}",            result: "Slightly large (~18px)" },
        { label: "small",       syntax: "{\\small note}",            result: "Small text (~14px)" },
        { label: "footnotesize",syntax: "{\\footnotesize detail}",   result: "Smaller text (~12px) — good for dates or footnotes" },
        { label: "Bold series", syntax: "{\\bfseries Bold text}",    result: "Bold — alternative to \\textbf{ }" },
        { label: "Italic shape",syntax: "{\\itshape Italic text}",   result: "Italic — alternative to \\textit{ }" },
        { label: "Combined",    syntax: "{\\large\\bfseries Title}", result: "You can combine size and weight commands inside the same { } block" },
      ],
    },
    {
      heading: "Alignment",
      items: [
        {
          label: "Centred block",
          syntax: "\\begin{center}\n  John Smith\n\\end{center}",
          result: "Centres the content horizontally — commonly used for the name header.",
        },
      ],
    },
    {
      heading: "Lists",
      items: [
        {
          label: "Bullet list",
          syntax: "\\begin{itemize}\n  \\item First achievement\n  \\item Second achievement\n\\end{itemize}",
          result: "Unordered bullet list",
        },
        {
          label: "Numbered list",
          syntax: "\\begin{enumerate}\n  \\item Step one\n  \\item Step two\n\\end{enumerate}",
          result: "Ordered numbered list",
        },
      ],
    },
    {
      heading: "Tables",
      items: [
        {
          label: "Simple table",
          syntax: "\\begin{tabular}{ll}\n  \\hline\n  Skill & Level \\\\\n  React & Expert \\\\\n\\end{tabular}",
          result: "Table with columns separated by & and rows ended by \\\\. The \\hline row becomes the header.",
          note: "Column format letters (l, r, c) are accepted but the app renders all columns the same width. Use for simple skills tables.",
        },
      ],
    },
    {
      heading: "Links",
      items: [
        { label: "Hyperlink with label", syntax: "\\href{https://github.com/you}{GitHub}", result: "Clickable link showing 'GitHub'" },
        { label: "Raw URL",              syntax: "\\url{https://github.com/you}",          result: "Clickable link showing the full URL" },
      ],
    },
    {
      heading: "Special Characters",
      items: [
        { label: "Ampersand",      syntax: "\\&",   result: "& — must be escaped in LaTeX" },
        { label: "Percent",        syntax: "\\%",   result: "%" },
        { label: "Hash",           syntax: "\\#",   result: "#" },
        { label: "Dollar sign",    syntax: "\\$",   result: "$" },
        { label: "Non-breaking space", syntax: "\\~", result: "A non-breaking space (prevents line wrap)" },
        { label: "Thin space",     syntax: "\\,",   result: "A small gap — useful between initials: J.\\,Smith" },
        { label: "Em dash",        syntax: "---",   result: "— (em dash)" },
        { label: "En dash",        syntax: "--",    result: "– (en dash) — use for date ranges: 2022--2024" },
        { label: "Bullet (in math mode)", syntax: "$\\bullet$", result: "• (bullet point — can be used as a separator)" },
        { label: "Centre dot",     syntax: "$\\cdot$", result: "· (centre dot — useful as a separator between items)" },
        { label: "Pipe separator", syntax: "$|$",   result: "| (vertical pipe)" },
      ],
    },
    {
      heading: "Ignored / Stripped Commands",
      items: [
        {
          label: "Layout commands (ignored)",
          syntax: "\\geometry{} \\vspace{} \\hspace{} \\noindent \\setlength{}{}",
          result: "These commands are silently removed. Use the margin/padding controls in the toolbar instead.",
        },
        {
          label: "Math blocks",
          syntax: "$E = mc^2$",
          result: "Inline math ($...$) is removed unless it contains one of the supported symbols (\\bullet, \\cdot, |).",
        },
        {
          label: "Unknown commands",
          syntax: "\\someUnknownCommand{text}",
          result: "Unknown single-argument commands fall back to showing just the argument text. Unknown zero-argument commands are removed.",
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  HTML + TAILWIND
// ─────────────────────────────────────────────────────────────────────────────

export const HTML_HELP: HelpSection = {
  id: "html",
  title: "HTML + Tailwind Mode",
  intro: `
HTML mode gives you full control. You write standard HTML and style it with Tailwind CSS utility classes. The preview loads Tailwind from CDN so all classes work instantly — no build step needed.

HTML sanitiser: DOMPurify (https://github.com/cure53/DOMPurify)
  — Malicious tags (script, iframe, object) and unsafe attributes are removed automatically.
  — Safe attributes allowed: href, src, alt, style, class, id, target, data-*

Tailwind CSS v3 via CDN (https://cdn.tailwindcss.com)
  — Full Tailwind v3 class reference: https://tailwindcss.com/docs
  — Responsive prefixes (sm:, md:, lg:) and dark: are stripped — the preview is always static A4.
  — Hover/focus/active variants are also stripped since the PDF has no interactivity.

Allowed HTML tags: h1–h6, p, br, hr, ul, ol, li, strong, em, b, i, a, span, div, section, header, code, pre, table, thead, tbody, tr, td, th
  `.trim(),
  groups: [
    {
      heading: "Page Layout",
      items: [
        {
          label: "Full-page wrapper",
          syntax: '<div class="max-w-2xl mx-auto px-8 py-10 font-sans text-sm text-gray-900">',
          result: "A centred content column with padding — a good starting wrapper for the whole resume.",
        },
        {
          label: "Two-column layout",
          syntax: '<div class="grid grid-cols-3 gap-6">\n  <div class="col-span-1"><!-- sidebar --></div>\n  <div class="col-span-2"><!-- main --></div>\n</div>',
          result: "A sidebar + main content layout using CSS Grid.",
        },
        {
          label: "Flex row (spread apart)",
          syntax: '<div class="flex justify-between items-baseline">',
          result: "Puts two items on the same line with maximum space between — great for 'Company Name' on the left and 'Date' on the right.",
        },
        {
          label: "Page break",
          syntax: '<div class="page-break"></div>',
          result: "Forces a new A4 page at this point in the PDF. The class page-break is built into the app.",
        },
      ],
    },
    {
      heading: "Typography",
      items: [
        { label: "Large name heading",  syntax: '<h1 class="text-3xl font-bold tracking-tight">John Smith</h1>', result: "Large bold heading — use for your name" },
        { label: "Section heading",     syntax: '<h2 class="text-base font-semibold uppercase tracking-widest border-b border-gray-300 pb-1 mb-3">Experience</h2>', result: "A spaced-out section divider with a bottom border" },
        { label: "Job title",           syntax: '<h3 class="font-semibold text-sm">Senior Engineer</h3>',        result: "A smaller heading for job titles" },
        { label: "Body paragraph",      syntax: '<p class="text-sm leading-relaxed text-gray-700">...</p>',       result: "Normal paragraph text" },
        { label: "Muted / secondary",   syntax: '<span class="text-xs text-gray-500">Jan 2022 – Present</span>', result: "Small grey text — good for dates or locations" },
        { label: "Bold inline",         syntax: '<strong class="font-semibold">React</strong>',                   result: "Bold a single word inline" },
        { label: "Italic inline",       syntax: '<em class="italic">Remote</em>',                                 result: "Italic a single word inline" },
      ],
    },
    {
      heading: "Spacing",
      items: [
        { label: "Margin bottom",  syntax: 'class="mb-2"',   result: "Add space below an element. mb-1=4px mb-2=8px mb-4=16px mb-6=24px" },
        { label: "Margin top",     syntax: 'class="mt-2"',   result: "Add space above an element" },
        { label: "Padding",        syntax: 'class="px-4 py-2"', result: "px = left+right padding, py = top+bottom padding" },
        { label: "Gap in flex/grid", syntax: 'class="gap-2"', result: "Space between children in a flex or grid container" },
      ],
    },
    {
      heading: "Colour",
      items: [
        { label: "Text colour",       syntax: 'class="text-blue-600"',    result: "Named colour — see https://tailwindcss.com/docs/text-color for the full palette (slate, gray, zinc, red, orange, amber, yellow, green, teal, blue, indigo, violet, purple, pink, rose)" },
        { label: "Arbitrary colour",  syntax: 'class="text-[#1a56db]"',   result: "Any hex colour using square-bracket syntax" },
        { label: "Background colour", syntax: 'class="bg-gray-50"',       result: "Background fill on an element" },
        { label: "Border colour",     syntax: 'class="border border-gray-200"', result: "A 1px border in a light grey" },
      ],
    },
    {
      heading: "Lists",
      items: [
        {
          label: "Bullet list",
          syntax: '<ul class="list-disc pl-5 space-y-1 text-sm">\n  <li>Achievement one</li>\n  <li>Achievement two</li>\n</ul>',
          result: "Disc-style bullet list with vertical spacing between items",
        },
        {
          label: "No-bullet list",
          syntax: '<ul class="space-y-1 text-sm">\n  <li>Item</li>\n</ul>',
          result: "List without bullet symbols — useful for clean skill tags",
        },
        {
          label: "Inline tag list",
          syntax: '<div class="flex flex-wrap gap-1.5">\n  <span class="px-2 py-0.5 bg-gray-100 rounded text-xs">React</span>\n</div>',
          result: "Pill-shaped skill tags in a wrapping row",
        },
      ],
    },
    {
      heading: "Tables",
      items: [
        {
          label: "Skills table",
          syntax: '<table class="w-full text-sm">\n  <tr>\n    <td class="font-medium w-1/3">Languages</td>\n    <td>JavaScript, TypeScript, Python</td>\n  </tr>\n</table>',
          result: "A borderless two-column table — left for category, right for values",
        },
      ],
    },
    {
      heading: "Links",
      items: [
        { label: "Hyperlink", syntax: '<a href="https://github.com/you" class="text-blue-600 underline">GitHub</a>', result: "Clickable link that opens in a new tab (base target=_blank is set automatically)" },
      ],
    },
    {
      heading: "Inline Style (when Tailwind isn't enough)",
      items: [
        {
          label: "Arbitrary font size",
          syntax: 'class="text-[10.5px]"',
          result: "Any CSS value in square brackets — e.g. text-[10.5px], leading-[1.4], mt-[3mm]",
          note: "This is standard Tailwind JIT syntax and works in the preview.",
        },
        {
          label: "Direct style attribute",
          syntax: '<span style="color:#e11d48;font-size:11px">text</span>',
          result: "Inline CSS always works as a fallback when there is no Tailwind class for what you need.",
        },
      ],
    },
    {
      heading: "What Does NOT Work",
      items: [
        { label: "Responsive prefixes", syntax: "sm: md: lg: xl:", result: "Stripped — the preview is always a fixed A4 width." },
        { label: "Dark mode",           syntax: "dark:",            result: "Stripped — PDFs are always light." },
        { label: "Hover / focus",       syntax: "hover: focus: active:", result: "Stripped — not relevant in a static PDF." },
        { label: "Animations",          syntax: "animate- transition duration- ease-", result: "Stripped — no animations in PDFs." },
        { label: "Scripts / iframes",   syntax: "<script> <iframe> <object>", result: "Removed by DOMPurify for security." },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  EXPORT — single object for easy import
// ─────────────────────────────────────────────────────────────────────────────

export const HELP = {
  general:  GENERAL_HELP,
  markdown: MARKDOWN_HELP,
  latex:    LATEX_HELP,
  html:     HTML_HELP,
} as const;
