// ─────────────────────────────────────────────────────────────────────────────
//  ResumeForge — Help & Reference
//  Imported by the Help modal; each section is a self-contained object so the
//  UI can render tabs / accordions without parsing raw text.
// ─────────────────────────────────────────────────────────────────────────────

export interface HelpSection {
  id: string;
  title: string;
  intro: string;
  groups: HelpGroup[];
}

export interface HelpGroup {
  heading: string;
  items: HelpItem[];
}

export interface HelpItem {
  label: string;
  syntax: string;
  result: string;
  note?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
//  GENERAL
// ─────────────────────────────────────────────────────────────────────────────

export const GENERAL_HELP = `
ResumeForge lets you write your resume in three formats — Markdown, LaTeX, or plain HTML — and see a live A4 preview as you type.

HOW IT WORKS
  1. Pick a mode (Markdown / LaTeX / HTML) from the toolbar.
  2. Write or paste your content in the left editor.
  3. The right panel shows a live preview that looks exactly like the printed PDF.
  4. Click any text in the preview to open the Style Panel on the right — you can change the text, font size, and colour directly, then click "↗ Go to code" to jump to that line in the editor.
  5. When you are happy, click "Export PDF" in the toolbar to download a print-ready PDF.

STYLE PANEL (click any text in preview)
  • Text      — edit the text content inline; changes are reflected in your source code automatically.
  • Size (px) — override the font size of that specific element.
  • Color     — pick a colour for that element.
  • ↗ Go to code — scrolls the editor to the exact line and highlights it in blue.

THEMES & FONTS
  • Every mode has a set of built-in themes (e.g. Classic, Modern, Minimal).
  • You can also pick a global font from the toolbar font picker — it overrides the theme font on every element.

EXPORT
  • The PDF is generated by printing the preview iframe, so what you see is exactly what you get.
  • Content that overflows the A4 width is clipped (it will not bleed into the margins).
`.trim();

// ─────────────────────────────────────────────────────────────────────────────
//  MARKDOWN
// ─────────────────────────────────────────────────────────────────────────────

export const MARKDOWN_HELP: HelpSection = {
  id: "markdown",
  title: "Markdown Mode",
  intro: `
Markdown is the easiest way to write a resume. You write plain text with simple symbols for formatting and the app converts it to a styled document automatically.

Parser: marked v14  (https://marked.js.org)
Spec:   GitHub Flavored Markdown (GFM) — tables, strikethrough, and task lists are all supported.
Docs:   https://marked.js.org/using_pro
        https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
  `.trim(),
  groups: [
    {
      heading: "Headings",
      items: [
        { label: "Section title (large)",  syntax: "# My Name",           result: "Large heading — use for your name at the top" },
        { label: "Section title (medium)", syntax: "## Experience",        result: "Medium heading — use for resume sections" },
        { label: "Sub-heading",            syntax: "### Job Title",        result: "Smaller heading — use for job titles or companies" },
        { label: "Small label",            syntax: "#### Detail",          result: "Smallest heading — rarely needed" },
      ],
    },
    {
      heading: "Text Formatting",
      items: [
        { label: "Bold",          syntax: "**bold text**",          result: "Bold text — great for company names or skills" },
        { label: "Italic",        syntax: "_italic text_",          result: "Italic text — good for job titles or emphasis" },
        { label: "Bold + Italic", syntax: "**_both_**",             result: "Bold and italic together" },
        { label: "Inline code",   syntax: "`JavaScript`",           result: "Monospace code text — useful for tech skills" },
        { label: "Horizontal rule (divider)", syntax: "---",        result: "A thin horizontal line to separate sections" },
      ],
    },
    {
      heading: "Lists",
      items: [
        { label: "Bullet list",   syntax: "- Did something\n- Did another thing", result: "Unordered bullet list — use for achievements or skills" },
        { label: "Numbered list", syntax: "1. First\n2. Second",    result: "Ordered numbered list" },
        { label: "Nested list",   syntax: "- Item\n  - Sub-item",   result: "Two spaces before the dash to indent" },
      ],
    },
    {
      heading: "Links",
      items: [
        { label: "Hyperlink",     syntax: "[GitHub](https://github.com/you)", result: "Clickable link — shows 'GitHub' as the label" },
        { label: "Bare URL",      syntax: "https://github.com/you",           result: "Raw URL — auto-linked in the preview" },
      ],
    },
    {
      heading: "Tables",
      items: [
        {
          label: "Table",
          syntax: "| Skill | Level |\n|-------|-------|\n| React | Expert |",
          result: "A table with borders — useful for skills matrices",
          note: "Columns are separated by | and the dashes row creates the header.",
        },
      ],
    },
    {
      heading: "Inline Style Override",
      items: [
        {
          label: "Custom colour / size on a word",
          syntax: '<span style="color:#e11d48;font-size:13px">Remote</span>',
          result: "Any inline HTML is accepted — wrap text in a <span> with a style attribute to override colour or size for just that word.",
          note: "This is the same HTML the Style Panel writes automatically when you use the color or size controls.",
        },
      ],
    },
    {
      heading: "Tips",
      items: [
        { label: "Blank line between blocks", syntax: "(empty line)", result: "Always leave a blank line between headings, paragraphs, and lists. Without it, content merges into one paragraph." },
        { label: "Non-breaking space",        syntax: "&nbsp;",        result: "Prevents a line break between two words — e.g. 'Jan&nbsp;2024'" },
        { label: "Em dash",                   syntax: "—",             result: "Paste the — character directly; it renders correctly." },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  LATEX
// ─────────────────────────────────────────────────────────────────────────────

export const LATEX_HELP: HelpSection = {
  id: "latex",
  title: "LaTeX Mode",
  intro: `
LaTeX mode gives you fine-grained control over layout using familiar LaTeX commands. The parser is a custom regex-based converter (built into this app — no external LaTeX engine is needed), so only a curated subset of commands is supported.

Parser: ResumeForge built-in LaTeX renderer (helper/parsers.ts → parseLatex)
  — NOT a full LaTeX engine. Unsupported commands are stripped silently.
  — For full LaTeX rendering see: https://www.overleaf.com

Sanitiser: DOMPurify (https://github.com/cure53/DOMPurify)
  — Scripts and unsafe attributes are stripped from the output for security.

Structure: Wrap all content inside \\begin{document} ... \\end{document}.
  — Anything outside this block (preamble, \\usepackage, etc.) is ignored.
  `.trim(),
  groups: [
    {
      heading: "Document Structure",
      items: [
        {
          label: "Document wrapper",
          syntax: "\\begin{document}\n  ...\n\\end{document}",
          result: "Everything inside this block is rendered. Content outside (preamble) is ignored.",
        },
        {
          label: "Comment (ignored)",
          syntax: "% This is a comment",
          result: "Lines starting with % are stripped — use them for notes to yourself.",
        },
        {
          label: "New page",
          syntax: "\\newpage",
          result: "Forces a page break at that position.",
        },
      ],
    },
    {
      heading: "Resume-Specific Commands (built-in)",
      items: [
        {
          label: "Section heading",
          syntax: "\\rsection{Experience}",
          result: "Renders a styled section heading using the active theme's h2 style.",
          note: "This is the preferred way to create section dividers. Style is controlled by the theme.",
        },
        {
          label: "Job entry",
          syntax: "\\rjob{Company Name}{Job Title}{Jan 2022 – Present}",
          result: "Renders a job block: company as h3, title as h4, date aligned on the right.",
          note: "Arguments: {company}{title}{date}",
        },
        {
          label: "Inline style override",
          syntax: "\\rfstyle{color: #e11d48; font-size: 13px}{Remote}",
          result: "Wraps the text in a <span> with the given CSS. This is what the Style Panel writes automatically.",
          note: "Arguments: {CSS properties}{text to style}",
        },
      ],
    },
    {
      heading: "Text Formatting",
      items: [
        { label: "Bold",         syntax: "\\textbf{text}",    result: "Bold text" },
        { label: "Italic",       syntax: "\\textit{text}",    result: "Italic text" },
        { label: "Emphasise",    syntax: "\\emph{text}",      result: "Italic (same as \\textit for resumes)" },
        { label: "Small caps",   syntax: "\\textsc{text}",    result: "UPPERCASE with wider letter-spacing — good for labels" },
        { label: "Line break",   syntax: "\\\\",              result: "Forces a line break (like pressing Enter once)" },
        { label: "Horizontal rule", syntax: "\\rule{\\linewidth}{0.4pt}", result: "A full-width horizontal divider line" },
      ],
    },
    {
      heading: "Font Size Commands (inside { })",
      items: [
        { label: "Huge",        syntax: "{\\Huge John Smith}",      result: "Very large text (~36px) — great for your name" },
        { label: "huge",        syntax: "{\\huge Section}",          result: "Large text (~30px)" },
        { label: "LARGE",       syntax: "{\\LARGE Title}",           result: "Larger text (~24px)" },
        { label: "Large",       syntax: "{\\Large Title}",           result: "Large text (~20px)" },
        { label: "large",       syntax: "{\\large text}",            result: "Slightly large (~18px)" },
        { label: "small",       syntax: "{\\small note}",            result: "Small text (~14px)" },
        { label: "footnotesize",syntax: "{\\footnotesize detail}",   result: "Smaller text (~12px) — good for dates or footnotes" },
        { label: "Bold series", syntax: "{\\bfseries Bold text}",    result: "Bold — alternative to \\textbf{ }" },
        { label: "Italic shape",syntax: "{\\itshape Italic text}",   result: "Italic — alternative to \\textit{ }" },
        { label: "Combined",    syntax: "{\\large\\bfseries Title}", result: "You can combine size and weight commands inside the same { } block" },
      ],
    },
    {
      heading: "Alignment",
      items: [
        {
          label: "Centred block",
          syntax: "\\begin{center}\n  John Smith\n\\end{center}",
          result: "Centres the content horizontally — commonly used for the name header.",
        },
      ],
    },
    {
      heading: "Lists",
      items: [
        {
          label: "Bullet list",
          syntax: "\\begin{itemize}\n  \\item First achievement\n  \\item Second achievement\n\\end{itemize}",
          result: "Unordered bullet list",
        },
        {
          label: "Numbered list",
          syntax: "\\begin{enumerate}\n  \\item Step one\n  \\item Step two\n\\end{enumerate}",
          result: "Ordered numbered list",
        },
      ],
    },
    {
      heading: "Tables",
      items: [
        {
          label: "Simple table",
          syntax: "\\begin{tabular}{ll}\n  \\hline\n  Skill & Level \\\\\n  React & Expert \\\\\n\\end{tabular}",
          result: "Table with columns separated by & and rows ended by \\\\. The \\hline row becomes the header.",
          note: "Column format letters (l, r, c) are accepted but the app renders all columns the same width. Use for simple skills tables.",
        },
      ],
    },
    {
      heading: "Links",
      items: [
        { label: "Hyperlink with label", syntax: "\\href{https://github.com/you}{GitHub}", result: "Clickable link showing 'GitHub'" },
        { label: "Raw URL",              syntax: "\\url{https://github.com/you}",          result: "Clickable link showing the full URL" },
      ],
    },
    {
      heading: "Special Characters",
      items: [
        { label: "Ampersand",      syntax: "\\&",   result: "& — must be escaped in LaTeX" },
        { label: "Percent",        syntax: "\\%",   result: "%" },
        { label: "Hash",           syntax: "\\#",   result: "#" },
        { label: "Dollar sign",    syntax: "\\$",   result: "$" },
        { label: "Non-breaking space", syntax: "\\~", result: "A non-breaking space (prevents line wrap)" },
        { label: "Thin space",     syntax: "\\,",   result: "A small gap — useful between initials: J.\\,Smith" },
        { label: "Em dash",        syntax: "---",   result: "— (em dash)" },
        { label: "En dash",        syntax: "--",    result: "– (en dash) — use for date ranges: 2022--2024" },
        { label: "Bullet (in math mode)", syntax: "$\\bullet$", result: "• (bullet point — can be used as a separator)" },
        { label: "Centre dot",     syntax: "$\\cdot$", result: "· (centre dot — useful as a separator between items)" },
        { label: "Pipe separator", syntax: "$|$",   result: "| (vertical pipe)" },
      ],
    },
    {
      heading: "Ignored / Stripped Commands",
      items: [
        {
          label: "Layout commands (ignored)",
          syntax: "\\geometry{} \\vspace{} \\hspace{} \\noindent \\setlength{}{}",
          result: "These commands are silently removed. Use the margin/padding controls in the toolbar instead.",
        },
        {
          label: "Math blocks",
          syntax: "$E = mc^2$",
          result: "Inline math ($...$) is removed unless it contains one of the supported symbols (\\bullet, \\cdot, |).",
        },
        {
          label: "Unknown commands",
          syntax: "\\someUnknownCommand{text}",
          result: "Unknown single-argument commands fall back to showing just the argument text. Unknown zero-argument commands are removed.",
        },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  HTML + TAILWIND
// ─────────────────────────────────────────────────────────────────────────────

export const HTML_HELP: HelpSection = {
  id: "html",
  title: "HTML + Tailwind Mode",
  intro: `
HTML mode gives you full control. You write standard HTML and style it with Tailwind CSS utility classes. The preview loads Tailwind from CDN so all classes work instantly — no build step needed.

HTML sanitiser: DOMPurify (https://github.com/cure53/DOMPurify)
  — Malicious tags (script, iframe, object) and unsafe attributes are removed automatically.
  — Safe attributes allowed: href, src, alt, style, class, id, target, data-*

Tailwind CSS v3 via CDN (https://cdn.tailwindcss.com)
  — Full Tailwind v3 class reference: https://tailwindcss.com/docs
  — Responsive prefixes (sm:, md:, lg:) and dark: are stripped — the preview is always static A4.
  — Hover/focus/active variants are also stripped since the PDF has no interactivity.

Allowed HTML tags: h1–h6, p, br, hr, ul, ol, li, strong, em, b, i, a, span, div, section, header, code, pre, table, thead, tbody, tr, td, th
  `.trim(),
  groups: [
    {
      heading: "Page Layout",
      items: [
        {
          label: "Full-page wrapper",
          syntax: '<div class="max-w-2xl mx-auto px-8 py-10 font-sans text-sm text-gray-900">',
          result: "A centred content column with padding — a good starting wrapper for the whole resume.",
        },
        {
          label: "Two-column layout",
          syntax: '<div class="grid grid-cols-3 gap-6">\n  <div class="col-span-1"><!-- sidebar --></div>\n  <div class="col-span-2"><!-- main --></div>\n</div>',
          result: "A sidebar + main content layout using CSS Grid.",
        },
        {
          label: "Flex row (spread apart)",
          syntax: '<div class="flex justify-between items-baseline">',
          result: "Puts two items on the same line with maximum space between — great for 'Company Name' on the left and 'Date' on the right.",
        },
        {
          label: "Page break",
          syntax: '<div class="page-break"></div>',
          result: "Forces a new A4 page at this point in the PDF. The class page-break is built into the app.",
        },
      ],
    },
    {
      heading: "Typography",
      items: [
        { label: "Large name heading",  syntax: '<h1 class="text-3xl font-bold tracking-tight">John Smith</h1>', result: "Large bold heading — use for your name" },
        { label: "Section heading",     syntax: '<h2 class="text-base font-semibold uppercase tracking-widest border-b border-gray-300 pb-1 mb-3">Experience</h2>', result: "A spaced-out section divider with a bottom border" },
        { label: "Job title",           syntax: '<h3 class="font-semibold text-sm">Senior Engineer</h3>',        result: "A smaller heading for job titles" },
        { label: "Body paragraph",      syntax: '<p class="text-sm leading-relaxed text-gray-700">...</p>',       result: "Normal paragraph text" },
        { label: "Muted / secondary",   syntax: '<span class="text-xs text-gray-500">Jan 2022 – Present</span>', result: "Small grey text — good for dates or locations" },
        { label: "Bold inline",         syntax: '<strong class="font-semibold">React</strong>',                   result: "Bold a single word inline" },
        { label: "Italic inline",       syntax: '<em class="italic">Remote</em>',                                 result: "Italic a single word inline" },
      ],
    },
    {
      heading: "Spacing",
      items: [
        { label: "Margin bottom",  syntax: 'class="mb-2"',   result: "Add space below an element. mb-1=4px mb-2=8px mb-4=16px mb-6=24px" },
        { label: "Margin top",     syntax: 'class="mt-2"',   result: "Add space above an element" },
        { label: "Padding",        syntax: 'class="px-4 py-2"', result: "px = left+right padding, py = top+bottom padding" },
        { label: "Gap in flex/grid", syntax: 'class="gap-2"', result: "Space between children in a flex or grid container" },
      ],
    },
    {
      heading: "Colour",
      items: [
        { label: "Text colour",       syntax: 'class="text-blue-600"',    result: "Named colour — see https://tailwindcss.com/docs/text-color for the full palette (slate, gray, zinc, red, orange, amber, yellow, green, teal, blue, indigo, violet, purple, pink, rose)" },
        { label: "Arbitrary colour",  syntax: 'class="text-[#1a56db]"',   result: "Any hex colour using square-bracket syntax" },
        { label: "Background colour", syntax: 'class="bg-gray-50"',       result: "Background fill on an element" },
        { label: "Border colour",     syntax: 'class="border border-gray-200"', result: "A 1px border in a light grey" },
      ],
    },
    {
      heading: "Lists",
      items: [
        {
          label: "Bullet list",
          syntax: '<ul class="list-disc pl-5 space-y-1 text-sm">\n  <li>Achievement one</li>\n  <li>Achievement two</li>\n</ul>',
          result: "Disc-style bullet list with vertical spacing between items",
        },
        {
          label: "No-bullet list",
          syntax: '<ul class="space-y-1 text-sm">\n  <li>Item</li>\n</ul>',
          result: "List without bullet symbols — useful for clean skill tags",
        },
        {
          label: "Inline tag list",
          syntax: '<div class="flex flex-wrap gap-1.5">\n  <span class="px-2 py-0.5 bg-gray-100 rounded text-xs">React</span>\n</div>',
          result: "Pill-shaped skill tags in a wrapping row",
        },
      ],
    },
    {
      heading: "Tables",
      items: [
        {
          label: "Skills table",
          syntax: '<table class="w-full text-sm">\n  <tr>\n    <td class="font-medium w-1/3">Languages</td>\n    <td>JavaScript, TypeScript, Python</td>\n  </tr>\n</table>',
          result: "A borderless two-column table — left for category, right for values",
        },
      ],
    },
    {
      heading: "Links",
      items: [
        { label: "Hyperlink", syntax: '<a href="https://github.com/you" class="text-blue-600 underline">GitHub</a>', result: "Clickable link that opens in a new tab (base target=_blank is set automatically)" },
      ],
    },
    {
      heading: "Inline Style (when Tailwind isn't enough)",
      items: [
        {
          label: "Arbitrary font size",
          syntax: 'class="text-[10.5px]"',
          result: "Any CSS value in square brackets — e.g. text-[10.5px], leading-[1.4], mt-[3mm]",
          note: "This is standard Tailwind JIT syntax and works in the preview.",
        },
        {
          label: "Direct style attribute",
          syntax: '<span style="color:#e11d48;font-size:11px">text</span>',
          result: "Inline CSS always works as a fallback when there is no Tailwind class for what you need.",
        },
      ],
    },
    {
      heading: "What Does NOT Work",
      items: [
        { label: "Responsive prefixes", syntax: "sm: md: lg: xl:", result: "Stripped — the preview is always a fixed A4 width." },
        { label: "Dark mode",           syntax: "dark:",            result: "Stripped — PDFs are always light." },
        { label: "Hover / focus",       syntax: "hover: focus: active:", result: "Stripped — not relevant in a static PDF." },
        { label: "Animations",          syntax: "animate- transition duration- ease-", result: "Stripped — no animations in PDFs." },
        { label: "Scripts / iframes",   syntax: "<script> <iframe> <object>", result: "Removed by DOMPurify for security." },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  EXPORT — single object for easy import
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
//  AI PROMPTS
//  Copy-paste prompts for generating resume templates with an AI assistant.
//  Brackets like [Your Name] mark places users should customise before pasting.
// ─────────────────────────────────────────────────────────────────────────────

export interface AiPrompt {
  id: string;
  mode: string;
  title: string;
  description: string;
  prompt: string;
}

export const AI_PROMPTS: AiPrompt[] = [
  /* ── MARKDOWN — FULL RESUME ────────────────────────────────────────── */
  {
    id: "markdown-full",
    mode: "Markdown",
    title: "Full resume — Markdown",
    description: "Generates a complete resume in Markdown that is fully compatible with ResumeForge's parser (marked v14 / GFM). Includes every constraint the renderer enforces.",
    prompt: `You are generating a resume in Markdown for an app called ResumeForge.
Copy this prompt, edit every [bracketed placeholder] with your own details, then paste it into any AI (ChatGPT, Claude, Gemini, etc.). Paste the AI output directly into ResumeForge's editor.

═══════════════════════════════════════════════════════════════
RESUMEFORGE MARKDOWN — PARSER & RENDERER CONSTRAINTS
The app parses Markdown with "marked" (GitHub Flavored Markdown).
The HTML output is then sanitised with DOMPurify.
Only these HTML tags survive sanitisation:
  h1 h2 h3 h4 h5 h6 p br hr ul ol li strong em b i a span div
  section header code pre table thead tbody tr td th
Only these attributes survive: href, src, alt, style, class, id, target, data-*
Tags like <script>, <iframe>, <img>, <form>, <button>, <input>,
<style>, <object>, <embed>, <svg>, <canvas> are STRIPPED.
═══════════════════════════════════════════════════════════════

OUTPUT FORMAT — follow these rules exactly:
1. Output ONLY raw Markdown. No code fences, no explanation, no preamble, no closing remarks.
2. The very first line must be: # [name] — this becomes the h1 heading.
3. Use ## for section headings (Summary, Experience, Education, Skills, Projects, Certifications — include only the sections the user supplies below).
4. Use ### for sub-entries (company names or project names within a section).
5. Use #### sparingly for sub-sub-entries (e.g. a sub-project under a company).

FORMATTING RULES:
- **bold** → company names, institution names, key terms, skill group labels.
- _italic_ or *italic* → job titles, degree names, dates.
- \`backtick\` → technical skill names inline (renders as <code> in monospace).
- - (dash) for unordered bullet lists. Each bullet = one line, no sub-bullets unless the user asks.
- 1. 2. 3. for ordered/numbered lists (rarely needed in resumes).
- --- (three dashes on their own line) → horizontal divider <hr> between major sections.
- [Label](URL) → clickable hyperlink. Use for LinkedIn, GitHub, portfolio, email (mailto:your@email.com).
- | Col1 | Col2 |  with a |---|---| header row → GFM table. Good for skills matrices.
- > blockquote → supported but has no special theme styling, so use sparingly.
- Leave a blank line between every heading, paragraph, and list. Without it content merges into one paragraph.

THINGS THAT DO NOT WORK (the parser or sanitiser strips them):
- No images (<img> is stripped). Do not use ![alt](url).
- No embedded HTML that uses stripped tags (script, iframe, form, button, input, svg, canvas, object, embed).
- No LaTeX syntax (\\textbf etc.) — this is Markdown mode, not LaTeX mode.
- No code fences (\`\`\`) for layout — only use \`backtick\` for inline code.
- No raw CSS classes on Markdown elements (classes are only usable in HTML mode).

INLINE STYLE OVERRIDE (optional, advanced):
  You CAN insert <span style="color:#e11d48;font-size:13px">text</span> directly
  in Markdown — the parser allows inline HTML, and DOMPurify keeps <span> + style.
  Use this ONLY if the user wants a specific colour or size on a word.

PAGE & PRINT CONSTRAINTS:
- The preview renders at A4 width (794 px / 210 mm). Body font is 11 pt.
- Aim for ONE A4 page (~400–600 words). If content is long, cut older roles or reduce bullets.
- For a page break (multi-page resumes only) insert: <div class="page-break"></div>
  on its own line — it forces a new printed page in the PDF export.
- The PDF is generated via the browser's print dialog, so what the user sees in the preview is exactly what prints.

═══════════════════════════════════════════════════════════════
MY DETAILS — edit every [bracket] below, then paste this whole prompt into AI.
Delete any section you don't need. Add more roles/projects by copying the block.
═══════════════════════════════════════════════════════════════

Full name: [Your Full Name]
Job title / role applying for: [Target Role, e.g. Senior Frontend Engineer]
Location: [City, Country  — or "Remote"]
Email: [your@email.com]
Phone: [+1 555 000 0000]
LinkedIn: [https://linkedin.com/in/yourprofile]
GitHub / Portfolio: [https://github.com/yourusername]

--- PROFESSIONAL SUMMARY (2–3 sentences) ---
[Describe who you are and what you bring. E.g. "Senior frontend engineer with 8 years building React applications at scale…"]

--- WORK EXPERIENCE (most recent first) ---
[Copy this block for each role:]
Company: [Company Name]
Title: [Job Title]
Dates: [Start – End, e.g. Jan 2021 – Present]
Location: [City or Remote]
Achievements (3–5 bullets, each starting with a strong action verb):
- [e.g. Led migration of monolith to microservices, reducing deploy time by 60%]
- [add more]

--- EDUCATION ---
[Degree, Institution, Graduation Year, GPA if notable]

--- SKILLS (comma-separated, grouped) ---
[Languages: JavaScript, TypeScript, Python
Frameworks: React, Next.js, Node.js
Tools: Docker, AWS, Git
Soft Skills: Leadership, Communication]

--- PROJECTS (optional) ---
[Project Name — one-line description — https://link]

--- CERTIFICATIONS (optional) ---
[Certification Name, Year]

Now generate the complete Markdown resume.`,
  },

  /* ── LATEX — FULL RESUME ───────────────────────────────────────────── */
  {
    id: "latex-full",
    mode: "LaTeX",
    title: "Full resume — LaTeX",
    description: "Generates a resume using ResumeForge's custom regex-based LaTeX renderer. Lists every supported and unsupported command so the AI never outputs broken syntax.",
    prompt: `You are generating a resume in LaTeX for an app called ResumeForge.
Copy this prompt, edit every [bracketed placeholder] with your own details, then paste it into any AI (ChatGPT, Claude, Gemini, etc.). Paste the AI output directly into ResumeForge's editor.

═══════════════════════════════════════════════════════════════
RESUMEFORGE LATEX — PARSER & RENDERER CONSTRAINTS
This is NOT a full LaTeX engine (no pdflatex / xelatex). It is a custom
regex-based parser built into the app (helper/parsers.ts → parseLatex).
Unsupported commands are silently STRIPPED. Only the commands listed
below actually render. The HTML output is then sanitised with DOMPurify.

After parsing, only these HTML tags survive:
  h1 h2 h3 h4 h5 h6 p br hr ul ol li strong em b i a span div
  section header code pre table thead tbody tr td th
Only these attributes survive: href, src, alt, style, class, id, target, data-*
═══════════════════════════════════════════════════════════════

OUTPUT FORMAT — follow these rules exactly:
1. Output ONLY raw LaTeX. No explanation, no preamble, no closing remarks.
2. Start with \\begin{document} and end with \\end{document}.
3. Do NOT include ANY preamble: no \\documentclass, \\usepackage, \\geometry,
   \\pagestyle, \\author, \\title, \\date, \\maketitle, or any setup commands.
   Everything outside \\begin{document}...\\end{document} is ignored by the parser.
4. Lines starting with % are treated as comments and stripped.

═══════════════════════════════════════════════════════════════
SUPPORTED COMMANDS — use ONLY these (anything else is stripped)
═══════════════════════════════════════════════════════════════

DOCUMENT & LAYOUT:
  \\begin{document} ... \\end{document}     wraps all content
  \\begin{center} ... \\end{center}          centres a block → <div class="text-center mb-4">
  \\\\                                        line break → <br>
  \\newpage                                   page break → <div class="page-break">

CUSTOM RESUME COMMANDS (ResumeForge-specific):
  \\rsection{Title}                          section heading → <h2> with theme styling
  \\rjob{Company}{Job Title}{Date Range}     job entry → <h3> company + date right-aligned, <h4> title
  \\rfstyle{CSS properties}{text}            inline style → <span style="CSS">text</span>
    Example: \\rfstyle{color: #e11d48; font-size: 13px}{Remote}

TEXT FORMATTING:
  \\textbf{text}                              bold → <strong>
  \\textit{text}                              italic → <em>
  \\emph{text}                                italic → <em> (same as \\textit)
  \\textsc{text}                              small caps → <span class="uppercase tracking-wider text-sm">

FONT SIZE COMMANDS (wrap text inside { }):
  {\\Huge text}         → text-4xl (~36 px)    great for your name
  {\\huge text}         → text-3xl (~30 px)
  {\\LARGE text}        → text-2xl (~24 px)
  {\\Large text}        → text-xl  (~20 px)
  {\\large text}        → text-lg  (~18 px)    good for taglines
  {\\normalsize text}   → (default size)
  {\\small text}        → text-sm  (~14 px)    good for contact lines
  {\\footnotesize text} → text-sm  (~12 px)    good for dates
  {\\scriptsize text}   → (very small)
  {\\tiny text}         → (very small)

FONT WEIGHT / SHAPE (can combine with size inside same { }):
  {\\bfseries text}     → font-bold           (alternative to \\textbf)
  {\\itshape text}      → italic              (alternative to \\textit)
  {\\large\\bfseries Title}  → large + bold   (combination example)

LINKS:
  \\href{https://url}{Label}                  → <a href="url">Label</a>
  \\url{https://url}                          → <a href="url">url</a>

LISTS:
  \\begin{itemize}                            unordered bullet list → <ul>
    \\item First bullet
    \\item Second bullet
  \\end{itemize}

  \\begin{enumerate}                          numbered list → <ol>
    \\item First
    \\item Second
  \\end{enumerate}
  NOTE: nested \\item sub-lists are NOT supported.

TABLES:
  \\begin{tabular}{ll}                        simple table → <table>
    \\hline                                    makes first row a header → <thead>
    Skill & Level \\\\
    React & Expert \\\\
  \\end{tabular}
  NOTE: column format letters (l, r, c) are parsed but all columns render the same width.
  Rows end with \\\\ or \\\\[skip]. Columns separated by &.

HORIZONTAL RULE:
  \\rule{\\linewidth}{0.4pt}                  → <hr>

SPECIAL CHARACTERS:
  \\&  → &        \\%  → %        \\#  → #        \\$  → $
  \\~  → non-breaking space       \\,  → thin space (good between initials)
  \\quad → two spaces             \\qquad → four spaces

DASHES:
  ---  → — (em dash)              --  → – (en dash, use for date ranges)

MATH-MODE SEPARATORS (only these work — all other math is stripped):
  $\\bullet$      → • bullet point separator
  $\\cdot$        → · centre dot separator
  $\\textbullet$  → • bullet
  $|$             → | pipe separator

═══════════════════════════════════════════════════════════════
COMMANDS THAT ARE SILENTLY STRIPPED (do NOT use):
═══════════════════════════════════════════════════════════════
\\documentclass  \\usepackage  \\geometry  \\pagestyle  \\thispagestyle
\\fancyhf  \\lhead  \\rhead  \\cfoot  \\lfoot  \\rfoot
\\renewcommand  \\newcommand  \\setlength  \\addtolength
\\vspace  \\vspace*  \\hspace  \\hspace*  \\noindent
\\centering  \\raggedright  \\raggedleft
\\hfill  \\hrulefill  \\dotfill  \\vfill
\\linewidth  \\textwidth (as standalone)
\\medskip  \\smallskip  \\bigskip
\\parindent  \\parskip
\\clearpage (use \\newpage instead)
\\multicols  \\minipage  \\parbox  \\tabularx  \\adjustbox
\\mdseries  \\upshape (removed silently)
Any math environment beyond the 4 separators above ($E=mc^2$ → stripped)
Any unknown \\command{arg} → shows just "arg" text
Any unknown \\command (no arg) → removed entirely

═══════════════════════════════════════════════════════════════
PAGE & PRINT CONSTRAINTS:
═══════════════════════════════════════════════════════════════
- The preview renders at A4 width (794 px / 210 mm). Body font is 11 pt.
- Default font: STIX Two Text (serif). The user can override via toolbar.
- Theme styles (heading colours, borders, spacing) are applied automatically
  via Tailwind classes — your LaTeX doesn't need to handle colours/spacing.
- Aim for ONE A4 page. If content is long, reduce bullets or cut old roles.
- \\newpage forces a page break for multi-page resumes.
- The PDF is generated via the browser's print dialog.

═══════════════════════════════════════════════════════════════
MY DETAILS — edit every [bracket] below, then paste this whole prompt into AI.
Delete any section you don't need. Add more roles/projects by copying the block.
═══════════════════════════════════════════════════════════════

Full name: [Your Full Name]
Job title / tagline: [Target Role or Professional Tagline]
Email: [your@email.com]
Phone: [+1 555 000 0000]
LinkedIn: [https://linkedin.com/in/yourprofile]
GitHub / Portfolio: [https://github.com/yourusername]
Location: [City, Country]

--- PROFESSIONAL SUMMARY (2–3 sentences) ---
[Describe who you are and what you bring]

--- WORK EXPERIENCE (most recent first) ---
[Copy this block for each role:]
Company: [Company Name]
Title: [Job Title]
Dates: [Start – End]
Achievements (3–5 bullets, each starting with a strong action verb):
- [e.g. Led migration of monolith to microservices, reducing deploy time by 60%]
- [add more]

--- EDUCATION ---
[Degree, Institution, Year]

--- SKILLS (grouped) ---
[Languages: ..., Frameworks: ..., Tools: ...]

--- PROJECTS (optional) ---
[Name — description — URL]

--- CERTIFICATIONS (optional) ---
[Name, Year]

STRUCTURE GUIDE — the generated LaTeX should follow this skeleton:
\\begin{document}
\\begin{center}
{\\Huge\\bfseries Name}\\\\
{\\large Tagline}\\\\[4pt]
{\\small email $\\bullet$ phone $\\bullet$ location $\\bullet$ \\href{url}{LinkedIn}}
\\end{center}
\\rule{\\linewidth}{0.4pt}
\\rsection{Summary}
...paragraph...
\\rsection{Experience}
\\rjob{Company}{Title}{Dates}
\\begin{itemize}
\\item Achievement...
\\end{itemize}
...more jobs...
\\rsection{Education}
...
\\rsection{Skills}
\\begin{tabular}{ll}
Category & Skill, Skill, Skill \\\\
\\end{tabular}
\\end{document}

Now generate the complete LaTeX resume.`,
  },

  /* ── HTML + TAILWIND — FULL RESUME ─────────────────────────────────── */
  {
    id: "html-full",
    mode: "HTML",
    title: "Full resume — HTML + Tailwind",
    description: "Generates a fully styled resume using HTML and Tailwind CSS v3. Includes the exact DOMPurify whitelist, stripped Tailwind variants, and A4 rendering constraints.",
    prompt: `You are generating a resume in HTML + Tailwind CSS for an app called ResumeForge.
Copy this prompt, edit every [bracketed placeholder] with your own details, then paste it into any AI (ChatGPT, Claude, Gemini, etc.). Paste the AI output directly into ResumeForge's editor.

═══════════════════════════════════════════════════════════════
RESUMEFORGE HTML — PARSER, SANITISER & RENDERER CONSTRAINTS
In HTML mode the app does NOT parse your markup — it passes it through
directly. However, two processing steps still apply:

1. DOMPURIFY SANITISATION — only these tags survive:
   h1 h2 h3 h4 h5 h6 p br hr ul ol li strong em b i a span div
   section header code pre table thead tbody tr td th
   STRIPPED tags (silently removed):
   script, style, iframe, img, form, input, button, textarea, select,
   object, embed, svg, canvas, video, audio, link, meta, base, noscript
   ALLOWED attributes: href, src, alt, style, class, id, target, data-*
   Everything else (onclick, onerror, onload, etc.) is removed.

2. TAILWIND CLASS STRIPPING — the app removes classes with these prefixes
   because they break in the static A4 iframe or PDF:
   STRIPPED variant prefixes:
     sm: md: lg: xl: 2xl:                (responsive breakpoints)
     hover: focus: focus-within:          (interactive states)
     focus-visible: active: visited:      (interactive states)
     checked: disabled:                   (form states)
     dark: print:                         (colour scheme / media)
     group-hover: group-focus:            (group variants)
     peer-hover: peer-focus:              (peer variants)
     motion-safe: motion-reduce:          (motion preferences)
     selection:                           (selection styling)
   STRIPPED utility classes:
     min-h-screen, h-screen, w-screen, min-w-screen, max-h-screen, max-w-screen
     transition-*, animate-*, duration-*, ease-*, delay-*
     will-change, cursor-*, scroll-smooth, scroll-auto
   Any class using these prefixes/patterns is silently removed before rendering.

3. TAILWIND CSS v3 is loaded from CDN (https://cdn.tailwindcss.com).
   All standard Tailwind v3 utility classes work (except the stripped ones above).
   JIT arbitrary-value syntax works: text-[10.5px], leading-[1.4], mt-[3mm], bg-[#1a56db].
═══════════════════════════════════════════════════════════════

OUTPUT FORMAT — follow these rules exactly:
1. Output ONLY raw HTML body content. No <!DOCTYPE>, <html>, <head>, <body>,
   <style>, or <script> tags. Just the inner content.
2. Use Tailwind CSS v3 utility classes for ALL styling.
3. You MAY use inline style="" for values Tailwind can't express
   (e.g. style="font-size:10.5px" or style="column-gap:6mm").
4. Do NOT use any stripped variant prefixes listed above.
5. Do NOT use <img> unless the user explicitly asks for photos.

PAGE & PRINT CONSTRAINTS:
- The preview iframe is fixed at A4 width: 794 px (210 mm).
- A4 height per page: 1123 px (297 mm).
- Default body font: DM Sans (sans-serif), 11 pt, line-height ~1.4.
  The user can override the font via the toolbar — your HTML doesn't
  need to set font-family (but you can if the user asks).
- Background is always white (#fff) and text defaults to black.
- print-color-adjust: exact is set, so background colours DO print.
- For a page break: <div class="page-break"></div>
  This forces a new A4 page in the PDF export.
- The PDF is generated via the browser's print dialog (iframe.print()).
  @media print rules are already injected — you do NOT need to add them.
- Overflow-x is hidden — content wider than 794 px is clipped.

RECOMMENDED WRAPPER:
<div class="max-w-[740px] mx-auto px-8 py-8 font-sans text-[11pt] text-gray-900 leading-relaxed">
  ...all content here...
</div>

USEFUL PATTERNS:
- Two-column layout:
    <div class="grid grid-cols-3 gap-6">
      <div class="col-span-1">sidebar</div>
      <div class="col-span-2">main</div>
    </div>
- Flex row (company left, date right):
    <div class="flex justify-between items-baseline">
      <h3 class="font-semibold">Company</h3>
      <span class="text-xs text-gray-500">Jan 2021 – Present</span>
    </div>
- Pill skill tags:
    <div class="flex flex-wrap gap-1.5">
      <span class="px-2 py-0.5 bg-gray-100 rounded text-xs">React</span>
    </div>
- Section heading with border:
    <h2 class="text-sm font-bold uppercase tracking-widest border-b border-gray-300 pb-1 mb-3">Experience</h2>
- Arbitrary hex colours:
    class="text-[#1a56db]"   class="bg-[#f0f4ff]"   class="border-[#1a56db]"

═══════════════════════════════════════════════════════════════
MY DETAILS — edit every [bracket] below, then paste this whole prompt into AI.
Delete any section you don't need. Add more roles by copying the block.
═══════════════════════════════════════════════════════════════

Full name: [Your Full Name]
Job title / tagline: [Target Role]
Email: [your@email.com]
Phone: [+1 555 000 0000]
LinkedIn: [https://linkedin.com/in/yourprofile]
GitHub / Portfolio: [https://github.com/yourusername]
Location: [City, Country]

LAYOUT STYLE I WANT:
[Choose one or describe your own:
  Option A — Classic single column: name + contact at top, <hr>, sections stacked
  Option B — Two column: narrow left sidebar (skills, contact, education) + wide right main
  Option C — Modern accent: coloured left border or top strip, section labels uppercase tracking-widest
  Option D — Minimal: no borders, generous whitespace, very clean typography
  Custom: describe your layout here]

COLOUR SCHEME (optional):
[e.g. "accent #1e40af (dark blue), headings #1e3a5f, body neutral grey" — or leave blank for monochrome]

--- PROFESSIONAL SUMMARY ---
[2–3 sentences]

--- WORK EXPERIENCE (most recent first) ---
[Copy this block for each role:]
Company: [Company Name]
Title: [Job Title]
Dates: [Start – End]
Location: [City or Remote]
Achievements:
- [bullet]
- [bullet]

--- EDUCATION ---
[Degree, Institution, Year, GPA if notable]

--- SKILLS (grouped) ---
[Languages: ..., Frameworks: ..., Tools: ..., Soft Skills: ...]

--- PROJECTS (optional) ---
[Name — description — URL]

--- CERTIFICATIONS (optional) ---
[Name, Year]

Now generate the complete HTML + Tailwind resume body.`,
  },

  /* ── MARKDOWN — SINGLE SECTION ─────────────────────────────────────── */
  {
    id: "markdown-section",
    mode: "Markdown",
    title: "Single section — Markdown",
    description: "Generates or rewrites just one section of your Markdown resume. Includes parser constraints so the output drops straight into ResumeForge.",
    prompt: `You are generating a SINGLE SECTION of a Markdown resume for ResumeForge.
Copy this prompt, edit the [brackets], paste into any AI, then paste the output into your existing resume in ResumeForge's editor.

PARSER CONSTRAINTS (ResumeForge uses marked / GFM + DOMPurify):
- Output ONLY raw Markdown for this section. No code fences, no explanation.
- Start with the ## section heading. Do not add other sections.
- Allowed formatting: **bold**, _italic_, \`code\`, - bullets, 1. numbered,
  [Label](URL) links, | table | rows |, --- divider.
- Inline HTML: <span style="...">text</span> is allowed for colour/size overrides.
- These tags are stripped: <img>, <script>, <iframe>, <form>, <button>, <svg>.
- Leave a blank line between the heading and the first paragraph/list.
- Each bullet = one line, no sub-bullets unless asked.
- Do not invent facts — use [square bracket placeholders] for blanks.

SECTION I WANT: [e.g. Experience / Skills / Summary / Projects / Education / Certifications]

MY CONTENT FOR THIS SECTION:
[
  Paste your raw details here, as messy or structured as you like.

  Example — Experience:
    Company: Acme Corp, Senior Engineer, Jan 2021 – Present
    - Rebuilt checkout flow, increased conversion 15%
    - Mentored team of 4 junior engineers

  Example — Skills:
    JavaScript, TypeScript, React, Next.js, Node.js, PostgreSQL, Docker, AWS, Figma
]

TONE: [Professional / Concise / Achievement-focused / Entry-level / Executive]

Now generate just this section in Markdown.`,
  },

  /* ── LATEX — SINGLE SECTION ────────────────────────────────────────── */
  {
    id: "latex-section",
    mode: "LaTeX",
    title: "Single section — LaTeX",
    description: "Generates or rewrites just one section using ResumeForge's custom LaTeX commands. Lists every supported command for the section.",
    prompt: `You are generating a SINGLE SECTION of a LaTeX resume for ResumeForge.
Copy this prompt, edit the [brackets], paste into any AI, then paste the output into your existing resume in ResumeForge's editor (between \\begin{document} and \\end{document}).

PARSER CONSTRAINTS (ResumeForge uses a custom regex parser, NOT a full LaTeX engine):
- Output ONLY raw LaTeX for this section. No explanation, no \\begin{document} wrapper.
- Start with \\rsection{Section Title}.
- SUPPORTED commands you may use:
    \\rsection{Title}                       section heading
    \\rjob{Company}{Title}{Dates}           job entry (for Experience sections)
    \\textbf{text}  \\textit{text}  \\emph{text}  \\textsc{text}
    {\\large text}  {\\small text}  {\\footnotesize text}  {\\bfseries text}
    \\href{url}{label}   \\url{url}
    \\begin{itemize} \\item ... \\end{itemize}
    \\begin{enumerate} \\item ... \\end{enumerate}
    \\begin{tabular}{ll} cell & cell \\\\ \\end{tabular}
    \\\\  (line break)    ---  (em dash)    --  (en dash)
    $\\bullet$ (•)   $\\cdot$ (·)   $|$ (|)
    \\& \\% \\# \\$ \\~ \\,
    \\rule{\\linewidth}{0.4pt}  (horizontal rule)
- DO NOT use: \\vspace, \\hspace, \\noindent, \\newcommand, \\minipage, \\parbox,
  \\multicols, \\tabularx, or any math beyond $\\bullet$/$\\cdot$/$|$.
- Nested \\item sub-lists are NOT supported.
- Do not invent facts — use [square bracket placeholders] for blanks.

SECTION I WANT: [e.g. Experience / Skills / Summary / Projects / Education / Certifications]

MY CONTENT FOR THIS SECTION:
[Paste your raw details here]

TONE: [Professional / Concise / Achievement-focused / Entry-level / Executive]

Now generate just this section in LaTeX.`,
  },

  /* ── HTML — SINGLE SECTION ─────────────────────────────────────────── */
  {
    id: "html-section",
    mode: "HTML",
    title: "Single section — HTML + Tailwind",
    description: "Generates or restyles just one section of your HTML resume. Includes the full DOMPurify whitelist and stripped Tailwind variants.",
    prompt: `You are generating a SINGLE SECTION of an HTML + Tailwind CSS resume for ResumeForge.
Copy this prompt, edit the [brackets], paste into any AI, then paste the output into your existing resume in ResumeForge's editor.

SANITISER & RENDERER CONSTRAINTS:
- Output ONLY raw HTML for the section. No explanation, no <html>/<head>/<body>/<style>/<script>.
- ALLOWED tags (DOMPurify whitelist):
    h1 h2 h3 h4 h5 h6 p br hr ul ol li strong em b i a span div
    section header code pre table thead tbody tr td th
- STRIPPED tags: script, style, iframe, img, form, input, button, svg, canvas, object, embed
- ALLOWED attributes: href, src, alt, style, class, id, target, data-*
- Use Tailwind CSS v3 classes. JIT arbitrary values work: text-[10.5px], bg-[#f0f4ff].
- STRIPPED Tailwind prefixes (removed before rendering):
    sm: md: lg: xl: 2xl: hover: focus: active: dark: print:
    group-hover: peer-hover: motion-safe: motion-reduce: etc.
- STRIPPED utilities: animate-*, transition-*, duration-*, ease-*,
    h-screen, w-screen, min-h-screen, cursor-*, scroll-smooth
- Inline style="" is fine for values Tailwind can't handle.
- A4 width is 794 px. Do not use viewport-relative units.

SECTION I WANT: [e.g. Experience / Skills / Header / Education / Projects]

STYLE PREFERENCE:
[e.g. "clean with a left blue border on each job entry" / "two-column skills table" /
"pill badges for skills" / "match my resume which uses text-gray-900 + accent blue-700"]

MY CONTENT FOR THIS SECTION:
[Paste your raw details here]

Now generate just this section in HTML + Tailwind.`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
//  EXPORT — single object for easy import
// ─────────────────────────────────────────────────────────────────────────────

export const HELP = {
  general:  GENERAL_HELP,
  markdown: MARKDOWN_HELP,
  latex:    LATEX_HELP,
  html:     HTML_HELP,
  aiPrompts: AI_PROMPTS,
} as const;
